theme: jekyll-theme-cayman
title: "Web Coding for Beginners: Population Graphs"
description: "Build a working web app to visualize population graphs for countries. In one day. With zero coding experience."
github:
  is_project_page: false
google_analytics: UA-3773912-9